In [1]:
from scipy.stats import randint, uniform

In [4]:
ri = randint(0,10) # 0 ~ 9 무작위 수
ri.rvs(11) # 0~9사이 무작위 수를 11개 생성

array([7, 6, 0, 9, 8, 8, 7, 4, 3, 0, 9])

In [5]:
import numpy as np

np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 갯수를 함께 반환

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 97, 102,  82,  85, 108, 117,  91, 113, 103, 102]))

In [6]:
ui = uniform(0, 1) # 0~1사이의 무작위 실수
ui.rvs(5) # 0~1사이 무작위 실수를 5개 생성

array([0.75263657, 0.15610765, 0.23341662, 0.22390733, 0.83885265])