In [1]:
# numpy 배열 브로드 캐스팅 기능
import numpy as np

In [7]:
# nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums = np.arange(1, 11)
"""
    np.arange(10) : 0~9
    np.arange(1 , 11) : 1 ~ 10
    np.arange(1, 11, 2) : 1, 3, 5, 7, 9
"""
nums = nums + 10
nums = nums * 2
nums

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [8]:
# 배열의 차원 변경, reshape
nums2= nums.reshape(2, 5) # 2행 5열
nums2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [10]:
nums3 = nums.reshape(5, 2) # 5행 2열
nums3

array([[22, 24],
       [26, 28],
       [30, 32],
       [34, 36],
       [38, 40]])

In [11]:
nums4 = nums.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [14]:
# nums5 = nums.reshape(10, 1) 
nums5 = nums.reshape(-1, 1) # 전체 열을 전체 행의 갯수
nums5

array([[22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40]])

In [15]:
nums

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [16]:
np.random.shuffle(nums)

In [18]:
nums

array([28, 24, 34, 26, 32, 36, 40, 38, 30, 22])

In [19]:
fruits = np.array(['사과', '오렌지', '바나나', '망고', '멜론'])

In [20]:
fruits[[1,2,3]]

array(['오렌지', '바나나', '망고'], dtype='<U3')

In [21]:
fruits[[False, True, False, True, False]] # 불리언 인덱싱

array(['오렌지', '망고'], dtype='<U3')